# Generated by Django 4.0.5 on 2022-07-25 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saxeli', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mta_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saxeli', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tan_Mshromeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saxeli', models.CharField(max_length=50)),
                ('Gvari', models.CharField(max_length=50)),
                ('Cit', models.CharField(max_length=50)),
                ('Sqesi', models.CharField(max_length=1)),
                ('Piradi_Nom', models.CharField(max_length=11)),
                ('Dab_Tar', models.DateField(default=datetime.datetime(2022, 7, 25, 15, 44, 18, 747474))),
                ('Vada', models.DateField(default=datetime.datetime(2022, 7, 25, 15, 44, 18, 747474))),
                ('Surati', models.ImageField(upload_to='')),
                ('Emaili', models.EmailField(max_length=254)),
                ('Departamenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushakta_baza.departamenti')),
            ],
        ),
        migrations.AddField(
            model_name='departamenti',
            name='Mta_Dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushakta_baza.mta_dep'),
        ),
    ]
