# Generated by Django 4.0.5 on 2022-07-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saxeli', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tan_Mshromeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saxeli', models.CharField(max_length=50)),
                ('Gvari', models.CharField(max_length=50)),
                ('Sqesi', models.CharField(max_length=50)),
                ('Dab_Tar', models.DateTimeField()),
                ('Emaili', models.EmailField(max_length=254)),
                ('Piradi_Nom', models.CharField(max_length=11)),
                ('Departamenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushakta_baza.departamenti')),
            ],
        ),
    ]
