# Generated by Django 4.0.5 on 2022-07-25 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushakta_baza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mta_dep',
            old_name='saxeli',
            new_name='Saxeli',
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Dab_Tar',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 15, 55, 27, 504645)),
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Vada',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 15, 55, 27, 504645)),
        ),
    ]
