# Generated by Django 4.0.5 on 2022-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushakta_baza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tan_mshromeli',
            name='Dab_Tar',
        ),
        migrations.RemoveField(
            model_name='tan_mshromeli',
            name='Sqesi',
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Piradi_Nom',
            field=models.CharField(max_length=12),
        ),
    ]
