# Generated by Django 4.0.5 on 2022-07-26 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushakta_baza', '0002_alter_tan_mshromeli_dab_tar_alter_tan_mshromeli_vada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Dab_Tar',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 23, 28, 51, 81728)),
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Vada',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 23, 28, 51, 81728)),
        ),
        migrations.CreateModel(
            name='Maxasiateblebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pasu_Mgeb', models.BooleanField()),
                ('Adre_Modis', models.BooleanField()),
                ('Saqmes_Aketebs', models.BooleanField()),
                ('Xatavs', models.BooleanField()),
                ('Mgeris', models.BooleanField()),
                ('Piri', models.ManyToManyField(to='mushakta_baza.tan_mshromeli')),
            ],
        ),
    ]
