# Generated by Django 4.0.5 on 2022-07-25 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushakta_baza', '0002_rename_saxeli_mta_dep_saxeli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Dab_Tar',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 15, 58, 34, 616192)),
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Vada',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 15, 58, 34, 617189)),
        ),
    ]
