# Generated by Django 4.0.5 on 2022-07-26 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushakta_baza', '0003_alter_tan_mshromeli_dab_tar_alter_tan_mshromeli_vada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxasiateblebi',
            name='Adre_Modis',
        ),
        migrations.RemoveField(
            model_name='maxasiateblebi',
            name='Mgeris',
        ),
        migrations.RemoveField(
            model_name='maxasiateblebi',
            name='Pasu_Mgeb',
        ),
        migrations.RemoveField(
            model_name='maxasiateblebi',
            name='Piri',
        ),
        migrations.RemoveField(
            model_name='maxasiateblebi',
            name='Saqmes_Aketebs',
        ),
        migrations.RemoveField(
            model_name='maxasiateblebi',
            name='Xatavs',
        ),
        migrations.AddField(
            model_name='maxasiateblebi',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tan_mshromeli',
            name='maxasiateblebi',
            field=models.ManyToManyField(to='mushakta_baza.maxasiateblebi'),
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Dab_Tar',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 23, 46, 1, 663926)),
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Vada',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 23, 46, 1, 663926)),
        ),
    ]
