# Generated by Django 4.0.5 on 2022-07-27 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushakta_baza', '0004_remove_maxasiateblebi_adre_modis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Dab_Tar',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 17, 28, 37, 838665)),
        ),
        migrations.AlterField(
            model_name='tan_mshromeli',
            name='Vada',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 17, 28, 37, 838665)),
        ),
    ]
